### ISSUE TITLE
Watchman reports missing entity sensor.my_car_info in service.yaml

### ISSUE THREAD

**Issue by BNWEIN** [msp1974/homeassistant-jlrincontrol#87] opened 2023-01-09 09:04 UTC
Im running some clean up on my HA and i noticed the sensor.my_car_info is mentioned in jlrincontrol/services.yaml but does not seem to be a live service or is missing?

**Comment by ismarslomic** [comment] 2023-01-09 09:35
The `sensor.my_car_info` is used as example name of the sensor in multiple service calls mentioned in the [services.yaml](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/custom_components/jlrincontrol/services.yaml). 

I guess that you can't find the `sensor.my_car_info` entity in your HA installation? The name of this sensor depends on what you have named you JLR InControl device, so you might not find exactly same name in your installation. However, if you still don't find this sensor you might try to reload the `Jaguar Landrover InControl` integration in Settings > Integration.

**Comment by BNWEIN** [comment] 2023-01-09 09:55
I see.

So what is happening is the new tool I am using to keep HA clean is finding the example sensors as missing sensors. I am using Watchman (https://github.com/dummylabs/thewatchman).

**Comment by ismarslomic** [comment] 2023-01-09 10:00
I have no experience with Watchman, but you can find similar information within HA itself within the Settings > Entities and the Status column which indicates which entities are Unavailable. Just make sure that you have checked the "Show unavailable entities".

**Comment by BNWEIN** [comment] 2023-01-09 10:13
HA doesnt show the entity. The entity doesnt exist, only in the services.yaml file in the custom component. What is the point of that services.yaml file? Is it just examples?  

Watchman is looking at that file, seeing there are entities mentioned that are not commented out, that dont exist in HA, and thats why its telling me about them. 

I assume the services.yaml file can either be commented out or removed?

**Comment by ismarslomic** [comment] 2023-01-09 10:20
The point with `service.yaml` is to _describe_ the interface of the provided service with this integration, you can read more about it in official HA documentation: https://developers.home-assistant.io/docs/dev_101_services/#service-descriptions. The actual implementation of services are in [services.py](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/custom_components/jlrincontrol/services.py)

The mentioned sensor name is just a example, that is displayed in the UI to the user when they select one of the service calls provided by this integration.

I suggest that you find a way to ignore scanning the `service.yaml` in Watchman. Please close the issue as this is not a bug.

**Closed as completed** 2023-01-09 10:29 UTC
Labels: question
