### ISSUE TITLE
Implementation of device_state_attributes

### ISSUE THREAD

**Issue by bobbinz** [msp1974/homeassistant-jlrincontrol#60] opened 2021-12-12 14:04 UTC
Hiya,

Just upgraded to 2021.12 and got the following warnings:

```
Entity sensor.jaguar_xe_range (<class 'custom_components.jlrincontrol.sensor.JLRVehicleRangeSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.jaguar_xe_status (<class 'custom_components.jlrincontrol.sensor.JLRVehicleStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.jaguar_xe_last_trip (<class 'custom_components.jlrincontrol.sensor.JLRVehicleLastTripSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity device_tracker.jaguar_xe_device_tracker (<class 'custom_components.jlrincontrol.device_tracker.JLRDeviceTracker'>) implements device_state_attributes. Please report it to the custom component author.
Entity lock.jaguar_xe_doors (<class 'custom_components.jlrincontrol.lock.JLRLock'>) implements device_state_attributes. Please report it to the custom component author.
```

I'm not exactly sure if it started with this version or not, ut anyway, I have done as I am told and reported it!

Adam

**Comment by Oc3anAri3s** [comment] 2021-12-21 19:08
Same on 2021.12.4. Can't recall seeing this error on previous versions. 

- Entity sensor.tyres (<class 'custom_components.jlrincontrol.sensor.JLRVehicleTyreSensor'>) implements device_state_attributes. Please report it to the custom component author.
- Entity sensor.service_info (<class 'custom_components.jlrincontrol.sensor.JLRVehicleServiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
- Entity sensor.range (<class 'custom_components.jlrincontrol.sensor.JLRVehicleRangeSensor'>) implements device_state_attributes. Please report it to the custom component author.
- Entity sensor.status (<class 'custom_components.jlrincontrol.sensor.JLRVehicleStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by ismarslomic** [comment] 2021-12-26 15:34
Same on **HA** `v2021.12.5` and **jlrincontrol** `v2.1.3`. I have Jaguar I-Pace 2021. 

I got these warning messages in logs:

```
Entity sensor.slomic_jag_ev_battery (<class 'custom_components.jlrincontrol.sensor.JLREVChargeSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.slomic_jag_battery (<class 'custom_components.jlrincontrol.sensor.JLREVBatterySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.slomic_jag_last_trip (<class 'custom_components.jlrincontrol.sensor.JLRVehicleLastTripSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity lock.slomic_jag_doors (<class 'custom_components.jlrincontrol.lock.JLRLock'>) implements device_state_attributes. Please report it to the custom component author.
Entity device_tracker.slomic_jag_device_tracker (<class 'custom_components.jlrincontrol.device_tracker.JLRDeviceTracker'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by ismarslomic** [comment] 2021-12-26 15:51
According to the [HA Helper API documentation,](http://dev-docs.home-assistant.io/en/master/api/helpers.html#homeassistant.helpers.entity.Entity.device_state_attributes) `device_state_attributes` are deprecated and replaced with `extra_state_attributes`

**Comment by ismarslomic** [comment] 2021-12-26 16:21
Verified locally that replacing `device_state_attributes` with `extra_state_attributes` in following files removed deprecation warning in logs:
- [device_tracker.py](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/custom_components/jlrincontrol/device_tracker.py)
- [lock.py](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/custom_components/jlrincontrol/lock.py)
- [sensor.py](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/custom_components/jlrincontrol/sensor.py)

@msp1974 if you could make me contributor of this repo, I can do these changes in repo and also try to set a side some time in the future to make sure this repo is maintained.

**Comment by msp1974** [comment] 2021-12-26 17:08
All, I have made a couple of updates to the integration to fix this issue and a PR from @seanauff.  As I cannot test, please can someone do and feedback any issues.  Thx

**Comment by ismarslomic** [comment] 2021-12-26 18:51
@msp1974 I can test, but how do I switch to `v2.1.4 `pre-release version in Hacs?

**Comment by seanauff** [comment] 2021-12-26 19:08
> @msp1974 I can test, but how do I switch to `v2.1.4 `pre-release version in Hacs?

Took me so long to find this. HACS changed their UI but didn't update docs. Use the 3 dot menu on the Integrations screen in HACS for this repo, select "redownload", check the "beta versions" checkbox. Then you can switch to the pre-release.

**Comment by ismarslomic** [comment] 2021-12-26 19:29
Tnx @seanauff! That was helpful. I managed to switch to `v2.1.4 pre-release`. I can confirm that warning logs about deprecation of `device_state_attributes` are gone. However the entity `Ev Battery` is shown as `Unavailable`, I guess it is replaced with entity `Battery`? Also, few info from `All Info` entity and `status` attribute has been moved to `core status` attribute. I guess this is caused by the upgrade to **jlrpy** `v1.4.0`? If so, then this is breaking change and should be reflected in change log and major version upgrade?

**Comment by ismarslomic** [comment] 2021-12-26 20:09
By the way, jlrpy has released [version 1.4.1](https://github.com/ardevd/jlrpy/releases/tag/v1.4.1) 5 days ago

**Comment by msp1974** [comment] 2022-04-26 13:04
@ismarslomic FYI - there is a v2.2.0beta released today (as a pre-release) which is using jlrpy 1.4.1.  I'm just awaiting some feedback for people using it to make sure it is good and then will release official version at the weekend.  If you would be kind enough to install and test it for me that would be really helpful.  Thx

**Comment by ismarslomic** [comment] 2022-04-26 13:06
Will do later today and report back! Thanks for keeping this integration updated!

**Comment by seanauff** [comment] 2022-04-27 00:07
No issues for me so far on the beta!

**Comment by ismarslomic** [comment] 2022-04-27 04:55
I dont see ant issue neither.

**Comment by msp1974** [comment] 2022-04-28 13:55
Thanks both.  v2.2.1 now released.  Will close this issue.

**Closed as completed by msp1974** 2022-04-28 13:55 UTC
