### ISSUE TITLE
After hassio update core-2021.5.0

### ISSUE THREAD

**Issue by palve55** [msp1974/homeassistant-jlrincontrol#57] opened 2021-05-06 19:48 UTC
2021-05-06 19:48:01 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'jlrincontrol'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'jlrincontrol'

**Comment by mariwing** [comment] 2021-05-07 06:23
Duplicate of #53 and fixed in PR #55 Could you @msp1974  please take and look and merge the PR? Thank you!

**Comment by palve55** [comment] 2021-05-07 06:59
Hi Mariwing, I merged it. It seems ok after restart.

Thanks

Paolo

 

Da: mariwing ***@***.***> 
Inviato: venerdì 7 maggio 2021 08:24
A: msp1974/homeassistant-jlrincontrol ***@***.***>
Cc: palve55 ***@***.***>; Author ***@***.***>
Oggetto: Re: [msp1974/homeassistant-jlrincontrol] After hassio update core-2021.5.0 (#57)

 

Duplicate of #53 <https://github.com/msp1974/homeassistant-jlrincontrol/issues/53>  and fixed in PR #55 <https://github.com/msp1974/homeassistant-jlrincontrol/pull/55>  Could you @msp1974 <https://github.com/msp1974>  please take and look and merge the PR? Thank you!

**Comment by palve55** [comment] 2021-05-07 20:07
Hello, after new core update there is an error: “jlrpy not found” 

Bye

Paolo

 

Da: mariwing ***@***.***> 
Inviato: venerdì 7 maggio 2021 08:24
A: msp1974/homeassistant-jlrincontrol ***@***.***>
Cc: palve55 ***@***.***>; Author ***@***.***>
Oggetto: Re: [msp1974/homeassistant-jlrincontrol] After hassio update core-2021.5.0 (#57)

 

Duplicate of #53 <https://github.com/msp1974/homeassistant-jlrincontrol/issues/53>  and fixed in PR #55 <https://github.com/msp1974/homeassistant-jlrincontrol/pull/55>  Could you @msp1974 <https://github.com/msp1974>  please take and look and merge the PR? Thank you!

**Comment by palve55** [comment] 2021-05-07 20:40
This is ok maybe

 

Da: mariwing ***@***.***> 
Inviato: venerdì 7 maggio 2021 08:24
A: msp1974/homeassistant-jlrincontrol ***@***.***>
Cc: palve55 ***@***.***>; Author ***@***.***>
Oggetto: Re: [msp1974/homeassistant-jlrincontrol] After hassio update core-2021.5.0 (#57)

 

Duplicate of #53 <https://github.com/msp1974/homeassistant-jlrincontrol/issues/53>  and fixed in PR #55 <https://github.com/msp1974/homeassistant-jlrincontrol/pull/55>  Could you @msp1974 <https://github.com/msp1974>  please take and look and merge the PR? Thank you!

**Comment by msp1974** [comment] 2021-05-07 22:27
Will mergeand update release over weekend.  Thanks Mark

**Comment by msp1974** [comment] 2021-05-23 12:09
Updated release done.

**Closed as completed by msp1974** 2021-05-23 12:09 UTC
