### ISSUE TITLE
Sensor "Range" reporting 0 km in 3.0.0 Beta 2

### ISSUE THREAD

**Issue by ismarslomic** [msp1974/homeassistant-jlrincontrol#118] opened 2024-02-02 19:45 UTC
The sensor Range reports `0 km` in 3.0.0 Beta 2, while in 2.2.5 it reports `369 km`.

Diagnostic file is uploaded in #117

**Comment by ismarslomic** [comment] 2024-02-02 20:00
I think this is caused by the `engine_type=ICE` in 3.0.0 Beta 2, while in 2.2.5 it was `Electric`.

I guess `ICE` is not correct engine type, otherwise we need to include this value in the if-statement of [line 355](https://github.com/msp1974/homeassistant-jlrincontrol/blob/dev/custom_components/jlrincontrol/sensor.py#L355)

**Comment by msp1974** [comment] 2024-02-02 20:53
This is caused by a typo in my fix for engine type determination.  It was setting your EV to ICE incorrectly as you say.  Will be fixed in beta3

**Comment by msp1974** [comment] 2024-02-02 20:56
If you want to pull the updates from dev and see if these issues are fixed?

**Comment by ismarslomic** [comment] 2024-02-02 21:21
Latest updated from dev did resolve Range issue! Well done!

**Closed as completed** 2024-02-02 21:23 UTC
