### ISSUE TITLE
Lock / Unlock does not work anymore

### ISSUE THREAD

**Issue by McFarTech** [msp1974/homeassistant-jlrincontrol#102] opened 2023-12-08 14:56 UTC
Hi. 

My Lock / Unlock does not seem to work using the intergration but is fine using the JLR Remote app

I have everything set from what i can see. Any suggestions? 

homeassistant.exceptions.InvalidStateError: Invalid state with length 285. State max length is 255 characters.
2023-12-08 15:14:39.081 ERROR (MainThread) [custom_components.jlrincontrol.services] Error calling service unlock on vehicle McFarlane Disco Sport. Error is 
2023-12-08 15:15:03.410 ERROR (MainThread) [custom_components.jlrincontrol.services] Error calling service unlock on vehicle McFarlane Disco Sport. Error is 
2023-12-08 15:15:41.179 DEBUG (MainThread) [custom_components.jlrincontrol.lock] Unlocking vehicle
2023-12-08 15:15:42.246 ERROR (MainThread) [custom_components.jlrincontrol.services] Error calling service unlock on vehicle McFarlane Disco Sport. Error is 
2023-12-08 15:15:42.776 DEBUG (MainThread) [custom_components.jlrincontrol] Received status data update for McFarlane Disco Sport
2023-12-08 15:15:43.141 DEBUG (MainThread) [custom_components.jlrincontrol] Received position data update for McFarlane Disco Sport
2023-12-08 15:15:43.142 DEBUG (MainThread) [custom_components.jlrincontrol] Privacy mode is enabled. Trip data will not be loaded for McFarlane Disco Sport
2023-12-08 15:15:43.142 INFO (MainThread) [custom_components.jlrincontrol] JLR InControl update received for McFarlane Disco Sport
2023-12-08 15:15:43.142 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Info
2023-12-08 15:15:43.143 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Windows
2023-12-08 15:15:43.143 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Alarm
2023-12-08 15:15:43.143 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Tyres
2023-12-08 15:15:43.144 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Service Info
2023-12-08 15:15:43.144 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Range
2023-12-08 15:15:43.144 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Status
2023-12-08 15:15:43.144 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport All Info
2023-12-08 15:15:43.146 DEBUG (MainThread) [custom_components.jlrincontrol.entity] Updating McFarlane Disco Sport Doors
2023-12-08 15:15:43.146 DEBUG (MainThread) [custom_components.jlrincontrol.device_tracker] Updating McFarlane Disco Sport Device Tracker

**Comment by hawkseye76** [comment] 2023-12-08 18:14
Same here. Nothing seems to have been working for a few days now.

**Comment by msp1974** [comment] 2023-12-08 19:33
Have you upgraded to HA 2023.12? This broke another integration I write?  Will have a look over weekend to see if mine has also stopped working. I have upgraded to 2023.12.

**Comment by McFarTech** [comment] 2023-12-08 19:48
Hi , Yes i am running 2023.12.0

**Comment by hawkseye76** [comment] 2023-12-08 21:00
I'm still on 2023.11.3

**Comment by OGB1952** [comment] 2023-12-09 13:41
I'm on HA 2023.12 and have also lost lock/unlock for some reason.  It was working OK up until a week or so ago, I'm afraid I can't say for sure when it stopped working as I only noticed the integration was showing my doors as being unlocked a few days ago, then discovered that lock/unlock wasn't working via HA (but is fine with the InControl app).

**Comment by McFarTech** [comment] 2023-12-09 15:15
Glad its not just me, Hopefully will get sorted.

**Comment by hawkseye76** [comment] 2023-12-11 13:57
looks like they changed the commands for lock and unlock.  the python api this is based on is broken as well.

**Comment by msp1974** [comment] 2023-12-11 17:38
Ok, had some time to look at this today and will issue a PR to @ardevd to fix the api.  Once he has been able to release this, I will issue an update which will resolve.

**Comment by ardevd** [comment] 2023-12-11 19:43
Thank you very much for the contribution! Will merge and update asap!

**Comment by McFarTech** [comment] 2023-12-11 20:09
Thank you so much guys for taking care of this issue.

**Comment by msp1974** [comment] 2023-12-11 22:01
v2.2.4 released which fixes the issue.  Thanks @ardevd for the quick merge of PR and new release.

**Comment by McFarTech** [comment] 2023-12-12 15:07
Thank you. All working again now.

**Comment by hawkseye76** [comment] 2023-12-12 16:19
Same here.  All is working as expected after update.  Thanks for the quick response!

**Comment by dblanc42** [comment] 2023-12-13 15:40
Thanks for the update. Just being curious, do you know what changed? Would it affect pre-conditioning and/or charging?

**Comment by msp1974** [comment] 2023-12-13 17:00
It was the content type header in the request was set at v2 and needed to be v3.  It is possible that the same applies to other requests. You will see an error in the logs however if this is the case. What issue are you having?

**Comment by dblanc42** [comment] 2023-12-17 16:51
Thanks for the quick reply, had missed it... 
It was more curiosity than anything else. I don't use lock/unlock much, but was wondering if the preconditioning might be broken maybe in the future, if the same applied

**Comment by OGB1952** [comment] 2023-12-17 18:09
Many thanks for sorting this, much appreciated.  I can confirm that preconditioning was also broken, as well as door locking, but is now working fine.

**Comment by ismarslomic** [comment] 2023-12-17 22:39
Closing this issue as it has been resolved! Thanks for reporting the bug and helping out on testing!

**Closed as completed by ismarslomic** 2023-12-17 22:39 UTC
Labels: bug
